jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
        working_directory:  ~/project/backend
        command: npm install
        
      - run:
        working_directory:  ~/project/backen
        command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
