jobs:
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          working_directory:  ~/project/backend
          command: npm install
        
      - run:
          working_directory:  ~/project/backend
          command: npm run test
      - run:
          working_directory:  ~/project/frontend-react
          command: npm install
        
      - run:
          working_directory:  ~/project/frontend-react
          command: npm run test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
